[MODEXPW-32] Added FTP object storage repository
folio-org/mod-data-export-worker pull request #115
Opened 2021-11-26 15:06 UTC by Dmitriy-Butramyou

## Purpose
Add FTP upload service

## Approach
- Added FTP upload service
- Created unit test

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-11-29 14:26 UTC, AndreiMPV approved these changes

2021-11-29 14:28 UTC, AndreiMPV requested changes
Need to check : Why pom is fully updated.

2021-11-30 06:04 UTC, AndreiMPV approved these changes
After checking **pom.xml** in the **"master"** branch I found that it was saved with Windows based "CLRF" character, but should be Unix based "LF"

2021-11-30 10:33 UTC, khandramai approved these changes

2021-11-30 10:36 UTC, khandramai commented on src/main/java/org/folio/dew/repository/FTPObjectStorageRepository.java
> +      if (ftpClient.login(username, password)) {
I can propose refactor this part of code - extract it to separate method to simplify code.

2021-12-02 07:44 UTC, merged