MODEXPW-256 eholdings export: Add package level token to export file
folio-org/mod-data-export-worker pull request #319
Opened 2022-09-27 07:47 UTC by Shans-Kaluhin

Add package level token to export fields

### Learning
https://issues.folio.org/browse/MODEXPW-256

2022-09-27 10:51 UTC, psmagin requested changes

2022-09-27 10:51 UTC, psmagin commented on src/main/java/org/folio/dew/batch/eholdings/EHoldingsToExportFormatMapper.java
> +    return token.getPrompt() + ':' + token.getValue();
There should be another separator according to requirements:
![image](https://user-images.githubusercontent.com/5904625/192506576-b69618e8-1659-44c9-b071-d32fa06100db.png)

2022-09-27 10:51 UTC, psmagin commented on src/test/resources/output/eholdings_package_export.csv
> +Package Note,Package Agreements,Provider Name,Provider Id,Package Name,Package Id,Package Type,Package Holdings Status,Package Content Type,Package Custom Coverage,Package Show To Patrons,Package Aut
Column label should be another one according to requirements:
![image](https://user-images.githubusercontent.com/5904625/192506858-43edf436-2514-4c13-aae3-12854f5b11d0.png)

2022-09-28 11:13 UTC, siarhei-charniak approved these changes

2022-09-28 13:11 UTC, viacheslavkol approved these changes

2022-09-28 23:13 UTC, merged