MODEXPW-386 - "Connection reset (SocketException)" error bulk editing Items on large bulk edit job
folio-org/mod-data-export-worker pull request #426
Opened 2023-03-16 08:06 UTC by siarhei-charniak

[MODEXPW-386](https://issues.folio.org/browse/MODEXPW-386) - "Connection reset (SocketException)" error bulk editing Items on large bulk edit job

## Approach
Improved logic

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] Check logging
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-03-17 15:21 UTC, TarasSpashchenko requested changes

2023-03-17 15:21 UTC, TarasSpashchenko commented on src/main/java/org/folio/dew/batch/JobCompletionNotificationListener.java
> +        // do nothing
Please add a log warning here

2023-03-21 07:00 UTC, siarhei-charniak commented on src/main/java/org/folio/dew/batch/JobCompletionNotificationListener.java
> +        // do nothing
Good catch, thanks!

2023-03-21 07:54 UTC, TarasSpashchenko approved these changes

2023-03-21 12:47 UTC, siarhei-charniak commented
<img width="1210" alt="Screenshot 2023-03-21 at 15 42 57" src="https://user-images.githubusercontent.com/60380420/226610274-9c9ba82e-df85-4726-9606-afa8ac086066.png">

2023-03-23 07:33 UTC, alekGbuz commented on src/test/java/org/folio/dew/BulkEditTest.java
> +    var tempDir = System.getProperty(TMP_DIR_PROPERTY) + PATH_SEPARATOR + springApplicationName + PATH_SEPARATOR + jobId;
Plz, use Path options to create path for directory, path separator in that case will be operational system independent.

2023-03-23 07:34 UTC, alekGbuz commented on src/main/java/org/folio/dew/controller/BulkEditController.java
> +    var tempDir = System.getProperty(TMP_DIR_PROPERTY) + PATH_SEPARATOR + springApplicationName + PATH_SEPARATOR + jobId;
Plz, use Path options to create path for directory, path separator in that case will be operational system independent.

2023-03-24 06:08 UTC, obozhko-folio approved these changes

2023-03-24 08:50 UTC, khandramai commented on src/test/java/org/folio/dew/controller/BulkEditControllerTest.java
> +  @Disabled
Why this test is disabled?

2023-03-24 11:23 UTC, merged